volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:18@sha256:4aabea78cf39b90e834caf3af7d602a18565f6fe2508705c8d01aa63245c2e20
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
