allowBuilds:
{%- if dkcutter.useTriggerDev %}
  "@depot/cli": true
{%- endif %}
{%- if dkcutter.authProvider == "clerk" %}
  "@clerk/shared": true
{%- endif %}
{%- if dkcutter.usePrisma %}
  "@prisma/engines": true
{%- endif %}
{%- if dkcutter.useTriggerDev %}
  esbuild: true
{%- endif %}
{%- if dkcutter.usePrisma %}
  prisma: true
{%- endif %}
{%- if dkcutter.useTriggerDev %}
  protobufjs: true
{%- endif %}
  unrs-resolver: true

minimumReleaseAge: 4320
