name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-code:
    name: Check Code/Commit - CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - name: Install dependencies
        run: bun install
      - name: Check code
        run: bun run check
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          bun commitlint /
          --from ${{ github.event.pull_request.base.sha }} /
          --to ${{ github.event.pull_request.head.sha }} /
          --verbose

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    name: "Test ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - name: Install dependencies
        run: bun install
      - name: Run tests with type checking
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: bun run test:typecheck
      - name: Run tests
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: bun run test
